os:
  - linux
sudo: false
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter packages get
script:
  - ./flutter/bin/flutter analyze --no-current-package --dartdocs $TRAVIS_BUILD_DIR/lib
  - ./flutter/bin/flutter test --coverage --coverage-path=lcov.info
cache:
  directories:
    - $HOME/.pub-cache
