addons:
  firefox: latest
  chrome: stable

language: dart
sudo: required

dart:
  - stable
  - beta
  - dev
before_script:
  - dart pub get

script:
  - ./flutter/bin/dart analyze
  - ./flutter/bin/flutter analyze
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
