analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    dead_code: warning 
    # allow having TODOs in the code
    todo: warning

  exclude:
    - "bin/cache/**"

linter:
  rules:
   - unnecessary_getters_setters